services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "30110:4173"
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      - VITE_API_MODE=${VITE_API_MODE}
    command: pnpm preview --host
